ARTIFACT_DIR=${BUILD_DIR}/Debug-${PLATFORM_NAME}
CARTHAGE_DIR=${PROJECT_DIR}/Carthage/Build/iOS
AMPCORE="AMPCore.framework"
AMPCORE_DSYM="${AMPCORE}.dsym"
CL="MyAMPClientLibrary.framework"
CL_DSYM="${CL}.dsym"
PREFIX="[workspace-frameworks]"

#This script copies the Frameworks generated by AMPCore and MyAMPClientLibrary to the Cartahge folder. It allows us to do step debugging with our workspace.

function update() {
    source=${ARTIFACT_DIR}/$1
    target=${CARTHAGE_DIR}/$1
    if [[ -d $source || -f $source ]]
    then
    
        if [[ -f $target || -d $target ]]
        then
            echo "$PREFIX $target exists..."
            if  [[ $source -ot $target ]]
            then
                echo "$PREFIX $target is newer than $source"
                exit 0
                else
                echo "$PREFIX $target is older than $source "
            fi
        else
            echo "$PREFIX $target is not found"
        fi
    
        echo "$PREFIX erasing old $target"
        rm -rf $target
        echo "$PREFIX copying $current "
        cp -r $source $target
        echo "$PREFIX erasing $source"
        rm -rf $source
    
    else
        echo "$PREFIX $source not found. skipping copy step (we're probably not in workspace)"
    fi
}


update ${AMPCORE}
update ${AMPCORE_DSYM}
update ${CL}
update ${CL_DSYM}
